version: "3.0"
services:
  web:
    build: .
    restart: unless-stopped
    container_name: griotte_web
    ports:
      - "8042:80"
      - "8443:443"
    volumes:
      - ./api:/app/api
      - ./frontend/dist:/app/frontend/dist
      - /ssl:/etc/ssl/certs
    environment:
      - APP_ENV=production
      - APP_URL=https://api.griotte.faborah.xyz
  db:
    image: mariadb:11.3
    restart: unless-stopped
    container_name: griotte_db
    ports:
      - "3342:3306"
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql





