version: "3.0"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8042:80"
  db:
    image: mariadb:11.3
    restart: unless-stopped
    ports:
      - "3342:3306"
    environment:
      MARIADB_DATABASE: demo
      MARIADB_USER: demo
      MARIADB_PASSWORD: demo
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql